// Code generated by tools/genimage; DO NOT EDIT.

package main

import "time"

// frames.rgb565 の各コマを描く範囲とコマ数、コマの間隔。
const (
	spriteX       = 75
	spriteY       = 46
	spriteW       = 133
	spriteH       = 148
	numFrames     = 12
	frameInterval = 120 * time.Millisecond
)
